export const designs = [
  {
    figmaLink:
      "https://www.figma.com/file/lIIDMGg3PQZiTm7L49be2D/SIH?type=design&node-id=0%3A1&mode=design&t=tuRsfLbZYqIucO8y-1",
    imageLink:
      "https://res.cloudinary.com/dwuzfbivo/image/upload/f_auto/v1711872075/portfolio/designs/design2_ygb9x6.png",
  },
  {
    figmaLink:
      "https://www.figma.com/file/qt8sXimxe3PDxTGpFXEfx4/Streeya?type=design&node-id=339%3A380&mode=design&t=o2DNjtENGCVEiY1o-1",
    imageLink:
      "https://res.cloudinary.com/dwuzfbivo/image/upload/f_auto/v1711872075/portfolio/designs/design1_orn5kw.png",
  },
  {
    figmaLink:
      "https://www.figma.com/file/jy9dlBnoItnKxPHuPEwtXG/Mama?type=design&node-id=124%3A142&mode=design&t=2eNbFatsGsuyzuxO-1",
    imageLink:
      "https://res.cloudinary.com/dwuzfbivo/image/upload/f_auto/v1711872077/portfolio/designs/design3_gcnvim.png",
  },
];
